name: Sync README with Website

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  sync_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch index.md from website
        run: curl -sS -o index.md https://milobanks.com/index.md

      - name: Modify Content
        run: |
          sed -i 's|This is my website, where I share my projects and things that I'\''ve done.|This is my GitHub account, where I work, keep mirrors of projects I work on, and contribute to various open source projects.|' index.md

      - name: Compare with README.md
        id: check_diff
        run: |
          if ! cmp -s index.md README.md; then
            echo "FILES_DIFFER=true" >> $GITHUB_ENV
          else
            echo "FILES_DIFFER=false" >> $GITHUB_ENV
          fi

      - name: Replace README.md
        if: env.FILES_DIFFER == 'true'
        run: mv index.md README.md

      - name: Commit and Push Changes
        if: env.FILES_DIFFER == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Automated update: Sync README.md with website (content adjusted)"
          git push
